### ISSUE TITLE
owner_org = Missing value

### ISSUE THREAD

**Issue by cphsolutionslab** [ckan/ckanext-harvest#132]
Running the latest master on CKAN 2.3 fails with the error:
ValidationError: None - {'owner_org': ['A organization must be supplied', 'Missing value'], 'name': ['Missing value']}

This is even though an organization is already set in the harvest resource config, from the dropbown in the GUI.

**Comment by cphsolutionslab** [comment]
Not an error in master branch.

**Comment by cphsolutionslab** [comment]
I was wrong, still occurs in the master branch.

**Comment by cphsolutionslab** [comment]
Could it be something similar https://github.com/ckan/ckanext-dcat/pull/27

**Comment by cphsolutionslab** [comment]
Perhaps related/relevant, this is my gather_consumer.log:

/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently suppo$
  sess._flush_warning("related attribute set")
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:37: SAWarning: Usage of the 'collection append' operation is not currently supported$
  sess._flush_warning("collection append")
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:1907: SAWarning: Attribute history events accumulated on 1 previously clean instances w$
  self._flush(objects)

**Comment by davidread** [comment]
Which harvest source type are you using? e.g. Harvesting from a CKAN, ISO19139, DCAT etc

While you're at it, show us your full harvest source config, gather_consumer.log & fetch_consumer.log.

**Comment by cphsolutionslab** [comment]
I'm harvesting from CKAN.

This is my fetch_consumer.log:

/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently suppo$
  sess._flush_warning("related attribute set")
2015-05-13 15:00:11,606 ERROR [ckanext.harvest.harvesters.base] None - {'owner_org': ['A organization must be supplied', 'Missing value'], 'name': ['Missing value']}
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 226, in _create_or_update_package
    new_package = get_action('package_create_rest')(context, package_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 1115, in package_create_rest
    dictized_after = _get_action('package_create')(context, dictized_package)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 212, in package_create
    context, {'package': data})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 465, in package_create_default_resource_views
    create_datastore_views=create_datastore_views)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/datapreview.py", line 303, in add_views_to_dataset_resources
    create_datastore_views)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/datapreview.py", line 269, in add_views_to_resource
    view)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 363, in resource_view_create
    raise ValidationError(errors)
ValidationError: None - {'owner_org': ['A organization must be supplied', 'Missing value'], 'name': ['Missing value']}

This is my gather_consumer.log:
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently suppo$
  sess._flush_warning("related attribute set")
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:37: SAWarning: Usage of the 'collection append' operation is not currently supported$
  sess._flush_warning("collection append")
/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py:1907: SAWarning: Attribute history events accumulated on 1 previously clean instances w$
  self._flush(objects)
2015-05-13 17:00:06,203 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-13 21:00:05,906 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-14 01:00:05,405 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-14 05:00:06,394 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-14 09:00:05,638 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-14 13:00:05,465 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-14 17:00:07,327 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-14 21:00:05,665 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-15 01:00:06,076 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-15 05:00:06,054 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-15 09:00:07,850 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-15 13:00:08,192 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-15 17:00:06,171 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-15 21:00:06,366 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-16 01:00:06,462 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-16 05:00:06,172 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-16 09:00:06,128 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-16 13:00:06,041 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-16 17:00:05,964 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-16 21:00:07,145 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-17 01:00:06,316 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-17 05:00:07,587 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-17 09:00:07,719 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-17 13:00:06,817 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-17 17:00:06,702 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-17 21:00:06,056 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-18 01:00:06,361 ERROR [ckanext.harvest.queue] Gather stage failed
2015-05-18 05:00:06,631 ERROR [ckanext.harvest.queue] Gather stage failed

**Comment by davidread** [comment]
Perhaps you harvesting an older CKAN or customized CKAN that doesn't require a dataset/package to have a value for owner_org i.e. be in an organization.

**Comment by cphsolutionslab** [comment]
I'm running CKAN 2.3 as mentioned in the beginning, just installed 2 weeks ago from scratch.

**Comment by davidread** [comment]
Perhaps you could provide details of the source CKAN? What is the URL?

**Comment by cphsolutionslab** [comment]
http://portal.opendata.dk/

**Comment by metaodi** [comment]
Just to clarify: Do use the `remote_orgs` config option?

**Comment by cphsolutionslab** [comment]
No. I've only got {"user": "harvest"}

**Comment by cphsolutionslab** [comment]
And harvest is admin.

**Comment by davidread** [comment]
Reading through the logic it suggests it would see if the org ID exists locally and fall back to the harvest source's org.

https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/harvesters/ckanharvester.py#L327-L364

I suggest you add some logging to see what it's doing here.

**Comment by amercader** [comment]
This sounds suspiciously familiar to https://github.com/ckan/ckan/issues/2421.

@cphsolutionslab Can you try and run the `release-v2.3.1` branch on CKAN core, restart all harvest processes and try again?

**Comment by cphsolutionslab** [comment]
I'm running a "production" environment installed from package. Can one download the 2.3.1 release yet and upgrade?

**Comment by cphsolutionslab** [comment]
I did apply the #2421 and it seemed to fix the issue. THANK you.

**Comment by amercader** [comment]
Glad to see it worked. FYI on a package install, until the next patch release is out, you can still got to the ckan directory (`/usr/lib/ckan/default/src/ckan`) and checkout the relevant release branch (in this case `release-v2.3.1`)
