### ISSUE TITLE
HELP: Installing ckan harvest on CKAN running on docker image

### ISSUE THREAD

**Issue by KidDavidacus** [ckan/ckanext-harvest#141]
I am trying to get this extension installed in my CKAN running on a docker image.

I was able to follow all the installion steps until running the command:
paster --plugin=ckanext-harvest harvester initdb --config=mysite.ini

However, I get an error everytime:

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 93, in run
    commands = get_commands()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 135, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/pluginlib.py", line 82, in resolve_plugins
    pkg_resources.require(plugin)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Not Found: ckanext-harvest (did you run python setup.py develop?)

Any reasons why this is happening?

**Comment by metaodi** [comment]
You need to install the extension with the activated virtualenv:

```bash
cd /path/to/ckanext-harvest
source /usr/lib/ckan/default/bin/activate
python setup.py develop
```

After that paster should be able to find the harvest extension.
