### ISSUE TITLE
Harvester crashes on very long extra fields

### ISSUE THREAD

**Issue by benjwadams** [ckan/ckanext-harvest#350]
The harvester fetch process will fail upon a Solr `SearchIndexError` being raised.   This will occur, for example, when a very long field is attempted to be indexed in a `solr.StrField`:

```
2019-01-25 23:23:01,894 ERROR [ckan.model.modification] Solr returned an error: (u'Solr responded with an error (HTTP 400): [Reason: Exception writing document id e50f1276e2eb6a5b92ffcf067931b60d to the index; possible analysis error: Document contains at least one immense term in field="lineage" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[50, 48, 49, 57, 45, 48, 49, 45, 50, 53, 32, 48, 54, 58, 52, 52, 58, 49, 55, 58, 32, 32, 65, 108, 108, 32, 112, 97, 114, 97]...\', original message: bytes can be at most 32766 in length; got 47848. Perhaps the document has an indexed string field (solr.StrField) which is too large]',)
Traceback (most recent call last):
  File "/usr/lib/ckan/venv/src/ckan/ckan/model/modification.py", line 77, in notify
    observer.notify(entity, operation)
--
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/venv/src/ckan/ckan/lib/search/index.py", line 301, in index_package
    raise SearchIndexError(msg)
SearchIndexError: Solr returned an error: (u'Solr responded with an error (HTTP 400): [Reason: Exception writing document id e50f1276e2eb6a5b92ffcf067931b60d to the index; possible analysis error: Document contains at least one immense term in field="lineage" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[50, 48, 49, 57, 45, 48, 49, 45, 50, 53, 32, 48, 54, 58, 52, 52, 58, 49, 55, 58, 32, 32, 65, 108, 108, 32, 112, 97, 114, 97]...\', original message: bytes can be at most 32766 in length; got 47848. Perhaps the document has an indexed string field (solr.StrField) which is too large]',)
```

Although this exception originates from the CKAN indexing code, it'd be best to continue on indexing other datasets and log the error as opposed to crashing the harvester process because a field exceeded a given length.

**Comment by metaodi** [comment]
@benjwadams I think this issue belongs on the ckan repository (https://github.com/ckan/ckan).

**Comment by benjwadams** [comment]
@metaodi, I was somewhat conflicted on whether to place this issue here or on the main CKAN repo.  I ultimately decided on here because in my opinion an exception really should be raised if Solr can't write an index from a CKAN dataset, but then the harvester does not handle the raised exception, so the entire harvester process dies.  Instead, when encountering an index that can't be written, the harvester could log an error message and continue harvesting the next datasets in the queue.
