### ISSUE TITLE
Python error when harvesters_info (list of installed plugins)

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ckan/ckanext-harvest#361]
Hi,

In my CKAN (using 2.7.5, I don't know if this fail occurs in 2.8), when I list my installed plugins:
paster --plugin=ckan plugin-info --config=/etc/myckan/production.ini

Then show:

```
harvest:
--------
Implements:
    ITranslation
    IDatasetForm
    IAuthFunctions
    IConfigurer
    IPackageController
    IRoutes
    IFacets
    ITemplateHelpers
        link_for_harvest_object(id=None, guid=None, text=None)
        harvest_frequencies()
        package_count_for_source(source_id)
            
                Returns the current package count for datasets associated with the given
                source id
                
        harvest_source_extra_fields()
        bootstrap_version()
        get_harvest_source(source_id=None)
        package_list_for_source(source_id)
            
                Creates a dataset list with the ones belonging to a particular harvest
                source.
            
                It calls the package_list snippet and the pager.
                
        harvester_types()
        harvesters_info()
Traceback (most recent call last):
  File "/usr/local/ckan/venv-myckan/bin/paster", line 10, in <module>
    sys.exit(run())
  File "/usr/local/ckan/venv-myckan/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/ckan/venv-myckan/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/local/ckan/venv-myckan/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/local/ckan/venv-myckan/src/ckan/ckan/lib/cli.py", line 1361, in command
    self.get_info()
  File "/usr/local/ckan/venv-myckan/src/ckan/ckan/lib/cli.py", line 1398, in get_info
    extra = self.actions(p['class'])
  File "/usr/local/ckan/venv-myckan/src/ckan/ckan/lib/cli.py", line 1407, in actions
    return self.function_info(actions)
  File "/usr/local/ckan/venv-myckan/src/ckan/ckan/lib/cli.py", line 1420, in function_info
    args_info = inspect.getargspec(fn)
  File "/usr/lib64/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <class 'ckanext.harvest.logic.action.create.InactiveSource'> is not a Python function
```

Howto fix it?

Regards,
Cesar Jorge

**Comment by leu2tm** [comment]
@cesarjorgemartinez did you figure out a solution this issue?

/ leu2tm
