### ISSUE TITLE
Timeouts when requesting api/action/harvest_source_list

### ISSUE THREAD

**Issue by kentsanggds** [ckan/ckanext-harvest#366]
## What

When we go to the api endpoint to show the harvest_source_list the page times out and we get a 504 timeout message.

I've identified that theres a series of longish queries to the database which appear to be the cause - 

https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/dictization.py#L149-L165

With over 600 harvest sources this page times out before the last query finishes.

## Possible solutions 

- optimise the queries so that we don't have so many joins, split up the query and do processing on the results to combine them
  - this might speed up things but not sure if will be enough to prevent the timeout and over time the number of harvest sources could increase to cause timeouts

- introduce paging, so only retrieve the first 50 harvest sources and provide metadata for the current result set and a link to the next set of results
  - this would be more future proof as it should be able to work with any increase in the number of harvest sources but will mean that users will need to be made aware of the change in response from `harvest_source_list` in order to retrieve all the harvest sources

**Comment by 6footdestiny** [comment]
FYI. Our stack trace example inluded below:

2019-06-05 09:39:00,146 [ajp-bio-8081-exec-2] WARN 129.215.242.68k ViewError - Handler execution resulted in exception

java.io.IOException: Server returned HTTP response code: 504 for URL: https://ckan.publishing.service.gov.uk/api/action/harvest_source_list?organization=a42aa1ab-8fbf-4fd
f-bbca-07570caa1cfb
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
at java.net.URL.openStream(URL.java:1045)
at edina.geodoc.service.waf.InternalDataGovWAFService.getAllOrgWAFs(InternalDataGovWAFService.java:45)
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:58)
at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:211)
at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:66)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
at edina.geodoc.service.waf.$Proxy20.getAllOrgWAFs(Unknown Source)
at edina.geodoc.service.waf.DataGovWAFService.getWAFs(DataGovWAFService.java:32)
at edina.geodoc.web.editor.ukme.DownloadController.referenceData(DownloadController.java:146)
at org.springframework.web.servlet.mvc.SimpleFormController.referenceData(SimpleFormController.java:218)


This was last tested and ran at 2019-06-05 09:39:00. It affects all users of the Location Editor (c. 200 local authorities plus 3rd sector and other public organisations like Ordnance Survey)
We require access to the Web Accessible Folder at the url queried so we can manage the published XML records at that location. We need read/write access.
