### ISSUE TITLE
Some harvester commands failing after 1.3.0 Upgrade

### ISSUE THREAD

**Issue by bonnland** [ckan/ckanext-harvest#409]
Hello,

I just upgraded our CKAN harvester to use version 1.3.0.   It was kind of urgent because harvest jobs were getting stuck without any clear explanation.   

Now I am able to start and stop WAF harvests from the Web UI, but certain command-line harvester commands are resulting in an error.   The commands in question are `harvester sources` and `harvester job-all`.  See the example below.

Is there something I have to do to update my WAF configuration?   Right now, I only define "harvest_user" and "read_only" parameters in my harvest source configuration.   

Any guidance is greatly appreciated.

I am using version 2.8 of CKAN, updated from the latest code on the 2.8 branch around January of 2020.

```
$ paster --plugin=ckanext-harvest harvester sources --config=/etc/ckan/default/development.ini
/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
2020-06-16 16:41:22,598 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2020-06-16 16:41:22,811 DEBUG [ckanext.harvest.model] Harvest tables already exist
2020-06-16 16:41:22,899 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2020-06-16 16:41:22,957 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2020-06-16 16:41:23,114 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2020-06-16 16:41:24,604 DEBUG [ckanext.harvest.model] Harvest tables already exist
2020-06-16 16:41:24,699 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2020-06-16 16:41:24,810 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 195, in command
    self.list_harvest_sources()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 326, in list_harvest_sources
    print(utils.list_sources(all))
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/utils.py", line 250, in list_sources
    sources = tk.get_action("harvest_source_list")(context, data_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/logic/action/get.py", line 129, in harvest_source_list
    organization_id = request.params.get('organization_id')
  File "/usr/lib/ckan/default/src/ckan/ckan/common.py", line 179, in params
    return self.args
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: request) has been registered for this thread

```

**Comment by bonnland** [comment]
Looking a little deeper, I am not sure how the following function (added on May 19, 2020) in `logic/action/get.py` is supposed to work.   How is a request object supposed to be instantiated for this function?   

The stack trace above says it all:  `TypeError: No object (name: request) has been registered for this thread`

```

@side_effect_free
def harvest_source_list(context, data_dict):
    '''
    TODO: Use package search
    '''

    organization_id = request.params.get('organization_id')
    limit = config.get('ckan.harvest.harvest_source_limit', 100)

    sources = _get_sources_for_user(context, data_dict, organization_id=organization_id, limit=limit)

    last_job_status = p.toolkit.asbool(data_dict.get('return_last_job_status', False))

    return [harvest_source_dictize(source, context, last_job_status) for source in sources]

```
