### ISSUE TITLE
CKAN 2.8 redis requirement conflicts with ckanext-harvester

### ISSUE THREAD

**Issue by scottlimmer** [ckan/ckanext-harvest#426]
CKAN 2.8.x has a requirement of `redis == 2.10.6`

ckanext-harvest throws the below error with this version of redis. Force upgrading redis (`pip install redis==3.5.3`) fixes this error, however the change from Redis 2.x to 3.x contains backwards incompatible changes, so I'm not sure what impact doing this would have on the broader CKAN installation.

```
(default) vagrant@ubuntu-xenial:/usr/lib/ckan/default/src/ckanext-harvest$ paster --plugin=ckanext-harvest harvester run_test test-ckan-harvest --config=/etc/ckan/default/production.ini
2020-11-12 02:42:32,444 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2020-11-12 02:42:32,467 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2020-11-12 02:42:32,476 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2020-11-12 02:42:32,490 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2020-11-12 02:42:32,493 DEBUG [ckanext.harvest.model] Harvest tables already exist
2020-11-12 02:42:33,370 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
2020-11-12 02:42:33,380 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2020-11-12 02:42:33,382 DEBUG [ckanext.harvest.model] Harvest tables already exist

2020-11-12 02:42:33,600 INFO  [ckanext.harvest.logic.action.create] Harvest job create: {'source_id': u'84d07d43-884f-40c8-be0f-42b480db229d'}
2020-11-12 02:42:33,608 INFO  [ckanext.harvest.logic.action.create] Harvest job saved 4ae3c793-8c6f-4b62-8ce4-8d916afd6e0a
2020-11-12 02:42:33,608 INFO  [ckanext.harvest.logic.action.update] Send job to gather queue: {'id': u'4ae3c793-8c6f-4b62-8ce4-8d916afd6e0a'}
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 233, in command
    self.run_test_harvest()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 391, in run_test_harvest
    utils.run_test_harvester(source_id_or_name, force_import)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/utils.py", line 382, in run_test_harvester
    "source_id": source["id"]
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/logic/action/create.py", line 120, in harvest_job_create
    context, {'id': job.id})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 809, in harvest_send_job_to_gather_queue
    publisher = get_gather_publisher()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 552, in get_gather_publisher
    return get_publisher(gather_routing_key)
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 229, in get_publisher
    connection = get_connection()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 43, in get_connection
    return get_connection_redis()
  File "/usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 82, in get_connection_redis
    encoding='utf-8',
TypeError: __init__() got an unexpected keyword argument 'encoding'

```

**Comment by m1h1902** [comment]
We are facing the same issue. However, we would like to keep the redis-version of ckan-core (2.10.6). How is it possible to use the harvester with redis 2.10?
