### ISSUE TITLE
after ckan 2.8 to 2.9 update + ckanext-harvester ,sometimes 404 on reharvest button

### ISSUE THREAD

**Issue by gallexme** [ckan/ckanext-harvest#440]
sometimes im getting
> 404 Not Found
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
but then another click works?

`2021-04-22 13:07:44,271 ERROR [ckan.config.middleware.flask_app] 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask_multistatic.py", line 96, in send_static_file
    raise NotFound()
NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2021-04-22 13:07:44,458 INFO  [ckan.config.middleware.flask_app]  /harvest/refresh/9f3ae3c3-4d1b-4a0f-a473-c3ebf11d36ce render time 0.188 seconds`

**Comment by gallexme** [comment]
Seems like its not always doing a POST when u click that "button" to /refresh cause its also a Link, and then uses GET?

and theres no GET route for that action
